# Generated by Django 4.2.3 on 2024-02-20 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorarea', models.IntegerField(default=0, null=True)),
                ('assembly', models.TextField(choices=[('Granite', 'Granite'), ('Marble', 'Marble'), ('Wood', 'Wood'), ('Custom', 'Custom')], default='Choose Assembly...', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoofAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roofarea', models.IntegerField(default=0, null=True)),
                ('assembly', models.TextField(choices=[('Reinforced Brick Concrete (RBC)', 'Reinforced Brick Concrete (RBC)'), ('Reinforced Cement Concrete (RCC)', 'Reinforced Cement Concrete (RCC)'), ('Fly Ash Bricks', 'Fly Ash Bricks'), ('Autoclaved Aerated Concrete (AAC)', 'Autoclaved Aerated Concrete (AAC)'), ('Custom', 'Custom')], default='Choose Assembly...', max_length=200, null=True)),
                ('insulation', models.TextField(choices=[('None', 'None'), ('NCM - Stone Wool', 'NCM - Stone Wool'), ('NCM - Glass Wool', 'NCM - Glass Wool'), ('Expanded Polystyrene (XPS/EPS)', 'Expanded Polystyrene (XPS/EPS)')], default='Choose Insulation...', max_length=200, null=True)),
                ('tile', models.TextField(choices=[('None', 'None'), ('Clay Roof Tile', 'Clay Roof Tile'), ('Cool Roof TIle', 'Cool Roof TIle')], default='Choose Tiles...', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WallAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallarea', models.IntegerField(default=0, null=True)),
                ('assembly', models.TextField(choices=[('Red Brick Construction', 'Red Brick Construction'), ('Reinforced Cement Concrete (RCC)', 'Reinforced Cement Concrete (RCC)'), ('Fly Ash Bricks', 'Fly Ash Bricks'), ('Autoclaved Aerated Concrete (AAC)', 'Autoclaved Aerated Concrete (AAC)'), ('Custom', 'Custom')], default='Choose Assembly...', max_length=200, null=True)),
                ('insulation', models.TextField(choices=[('None', 'None'), ('NCM - Stone Wool', 'NCM - Stone Wool'), ('NCM - Glass Wool', 'NCM - Glass Wool'), ('Expanded Polystyrene (XPS/EPS)', 'Expanded Polystyrene (XPS/EPS)')], default='Choose Insulation...', max_length=200, null=True)),
                ('tile', models.TextField(choices=[('None', 'None'), ('Ceramic Tile', 'Ceramic Tile')], default='Choose Tiles...', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindowAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windowarea', models.IntegerField(default=0, null=True)),
                ('glass', models.TextField(choices=[('Single Glazed Unit (SGU)', 'Single Glazed Unit (SGU)'), ('Double Glazed Unit (DGU)', 'Double Glazed Unit (DGU)')], default='Choose Glass...', max_length=200, null=True)),
                ('frame', models.TextField(choices=[('Single Glazed Unit (SGU)', 'Single Glazed Unit (SGU)'), ('Double Glazed Unit (DGU)', 'Double Glazed Unit (DGU)')], default='Choose Frame...', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='structuralarea',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='floorassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.floorassembly'),
        ),
        migrations.AddField(
            model_name='building',
            name='roofassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.roofassembly'),
        ),
        migrations.AddField(
            model_name='building',
            name='wallassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.wallassembly'),
        ),
        migrations.AddField(
            model_name='building',
            name='windowassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.windowassembly'),
        ),
    ]
