# Generated by Django 4.2.3 on 2024-02-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_building_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowassembly',
            name='frame',
            field=models.TextField(choices=[('Aluminium', 'Aluminium'), ('Wood', 'Wood')], default='Choose Frame...', max_length=200, null=True),
        ),
    ]
