# Generated by Django 4.2.3 on 2024-02-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_assembly_floorassembly_fassembly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuralAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structuralarea', models.IntegerField(default=0, null=True)),
                ('sassembly', models.TextField(choices=[('Concrete & Rebar', 'Concrete & Rebar')], default='Choose Assembly...', max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='structuralarea',
        ),
        migrations.AddField(
            model_name='building',
            name='structuralassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.structuralassembly'),
        ),
    ]
