# Generated by Django 4.2.3 on 2024-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_structuralassembly_remove_building_structuralarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorassembly',
            name='floorec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='roofassembly',
            name='roofec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='structuralassembly',
            name='structuralec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wallassembly',
            name='wallec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='windowassembly',
            name='windowec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
