# Generated by Django 4.2.3 on 2024-02-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_rename_insulation_roofassembly_roofinsulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='climatezone',
            field=models.TextField(choices=[('Hot & Dry', 'Hot & Dry'), ('Composite', 'Composite'), ('Warm & Humid', 'Warm & Humid'), ('Temperate', 'Temperate'), ('Cold', 'Cold')], default='Choose BHK...', max_length=200, null=True),
        ),
    ]
