# Generated by Django 4.2.3 on 2024-03-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_building_climatezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='acctype',
            field=models.TextField(choices=[('Flat (Standalone)', 'Flat (Standalone)'), ('Flat (Complex)', 'Flat (Complex)'), ('Rented', 'Rented'), ('House', 'House')], default='Choose Type...', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='face',
            field=models.TextField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], default='Choose Face Direction...', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='floor',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='floorcount',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='yourfloor',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='structuralassembly',
            name='sassembly',
            field=models.TextField(choices=[('Reinforced Cement Concrete (RCC)', 'Reinforced Cement Concrete (RCC)')], default='Choose Assembly...', max_length=200, null=True),
        ),
    ]
