# Generated by Django 4.2.3 on 2024-04-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_floorassembly_floorarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='gwp',
            field=models.FloatField(default=0, null=True),
        ),
    ]
